# Generated by Django 5.0.14 on 2026-06-13 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='message_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(
                choices=[
                    ('draft', 'Draft'),
                    ('pending_approval', 'Pending Approval'),
                    ('approved', 'Approved'),
                    ('email_sent', 'Email Sent'),
                    ('sent', 'Sent'),
                    ('waiting_confirmation', 'Waiting Confirmation'),
                    ('confirmed', 'Confirmed'),
                    ('rejected', 'Rejected'),
                    ('cancelled', 'Cancelled'),
                    ('failed', 'Failed'),
                    ('timeout', 'Timeout'),
                ],
                default='draft',
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name='PurchaseOrderWorkflow',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('draft', 'Draft'),
                            ('pending_approval', 'Pending Approval'),
                            ('approved', 'Approved'),
                            ('email_sent', 'Email Sent'),
                            ('waiting_confirmation', 'Waiting Confirmation'),
                            ('confirmed', 'Confirmed'),
                            ('rejected', 'Rejected'),
                            ('failed', 'Failed'),
                            ('timeout', 'Timeout'),
                        ],
                        default='draft',
                        max_length=20,
                    ),
                ),
                ('message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('polling_attempts', models.IntegerField(default=0)),
                ('last_poll_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'purchase_order',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='workflow',
                        to='purchasing.purchaseorder',
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
