# Generated by Django 5.0.14 on 2026-06-17 18:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0002_remove_salesrecord_inventory_s_sku_id_92dcd2_idx_and_more'),
        ('purchasing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['sku'], name='purchasing__sku_id_44310b_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier'], name='purchasing__supplie_83eac8_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['requested_by'], name='purchasing__request_f551a7_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['approved_by'], name='purchasing__approve_e6698e_idx'),
        ),
    ]
