# Generated by Django 5.0.14 on 2026-06-13 11:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-created_at']},
        ),
    ]
