# Generated by Django 5.0.14 on 2026-06-15 14:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0004_product_idx_product_active_created_and_more'),
        ('purchasing', '0002_purchaseorder_confirmed_at_purchaseorder_message_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status', '-created_at'], name='idx_po_status_created'),
        ),
    ]
