# Generated by Django 5.0.14 on 2026-06-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('purchasing', '0002_alter_purchaseorder_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
