# Generated by Django 5.0.14 on 2026-06-17 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_purchaseorder_idx_po_status_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'purchase order', 'verbose_name_plural': 'purchase orders'},
        ),
    ]
