# Generated by Django 5.0.14 on 2026-06-13 18:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('purchasing', '0003_purchaseorder_confirmed_at_purchaseorder_po_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
