# Generated by Django 5.0.14 on 2026-06-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'agent run',
                'verbose_name_plural': 'agent runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('USER_LOGIN', 'User Login'), ('PO_CREATED', 'Po Created'), ('PO_APPROVED', 'Po Approved'), ('PO_REJECTED', 'Po Rejected'), ('PO_SENT', 'Po Sent'), ('STOCK_ADJUSTED', 'Stock Adjusted'), ('PRODUCT_CREATED', 'Product Created'), ('PRODUCT_UPDATED', 'Product Updated'), ('INVOICE_CONFIRMED', 'Invoice Confirmed'), ('INVOICE_REJECTED', 'Invoice Rejected'), ('PROMPT_INJECTION_ATTEMPT', 'Prompt Injection Attempt'), ('AI_RAG_QUERY', 'Ai Rag Query'), ('AI_NL_QUERY', 'Ai Nl Query'), ('AI_CHAT_QUERY', 'Ai Chat Query'), ('VISION_EXTRACTION_FAILED', 'Vision Extraction Failed'), ('AGENT_RUN_COMPLETED', 'Agent Run Completed'), ('EMAIL_DELIVERY_FAILED', 'Email Delivery Failed'), ('SUPPLIER_TIMEOUT', 'Supplier Timeout')], max_length=100)),
                ('entity_type', models.CharField(blank=True, max_length=100)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('data_snapshot', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
