# Generated by Django 5.0.14 on 2026-06-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('agent_name', models.CharField(max_length=100)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('running', 'Running'),
                            ('completed', 'Completed'),
                            ('failed', 'Failed'),
                        ],
                        default='pending',
                        max_length=20,
                    ),
                ),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='event',
            field=models.CharField(
                choices=[
                    ('USER_LOGIN', 'User Login'),
                    ('PO_CREATED', 'Po Created'),
                    ('PO_APPROVED', 'Po Approved'),
                    ('PO_REJECTED', 'Po Rejected'),
                    ('PO_SENT', 'Po Sent'),
                    ('STOCK_ADJUSTED', 'Stock Adjusted'),
                    ('PRODUCT_CREATED', 'Product Created'),
                    ('PRODUCT_UPDATED', 'Product Updated'),
                    ('INVOICE_CONFIRMED', 'Invoice Confirmed'),
                    ('INVOICE_REJECTED', 'Invoice Rejected'),
                    ('PROMPT_INJECTION_ATTEMPT', 'Prompt Injection Attempt'),
                    ('AI_RAG_QUERY', 'Ai Rag Query'),
                    ('VISION_EXTRACTION_FAILED', 'Vision Extraction Failed'),
                    ('AGENT_RUN_COMPLETED', 'Agent Run Completed'),
                ],
                max_length=100,
            ),
        ),
    ]
