# Generated by Django 5.0.14 on 2026-06-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentrun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['status', 'created_at'], name='agentrun_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(
                fields=['agent_name', 'created_at'], name='agentrun_name_created_idx'
            ),
        ),
    ]
