# Generated by Django 5.0.14 on 2026-06-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0003_agentrun_alter_auditlog_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='event',
            field=models.CharField(
                choices=[
                    ('USER_LOGIN', 'User Login'),
                    ('PO_CREATED', 'Po Created'),
                    ('PO_APPROVED', 'Po Approved'),
                    ('PO_REJECTED', 'Po Rejected'),
                    ('PO_SENT', 'Po Sent'),
                    ('STOCK_ADJUSTED', 'Stock Adjusted'),
                    ('PRODUCT_CREATED', 'Product Created'),
                    ('PRODUCT_UPDATED', 'Product Updated'),
                    ('INVOICE_CONFIRMED', 'Invoice Confirmed'),
                    ('INVOICE_REJECTED', 'Invoice Rejected'),
                    ('PROMPT_INJECTION_ATTEMPT', 'Prompt Injection Attempt'),
                    ('AI_RAG_QUERY', 'Ai Rag Query'),
                    ('VISION_EXTRACTION_FAILED', 'Vision Extraction Failed'),
                    ('AGENT_RUN_COMPLETED', 'Agent Run Completed'),
                    ('EMAIL_DELIVERY_FAILED', 'Email Delivery Failed'),
                    ('SUPPLIER_TIMEOUT', 'Supplier Timeout'),
                ],
                max_length=100,
            ),
        ),
    ]
