# Generated by Django 5.0.14 on 2026-06-17 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_alter_auditlog_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentrun',
            options={'ordering': ['-created_at'], 'verbose_name': 'agent run', 'verbose_name_plural': 'agent runs'},
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'audit log', 'verbose_name_plural': 'audit logs'},
        ),
    ]
