# Generated by Django 5.0.14 on 2026-06-17 15:52

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            'CREATE EXTENSION IF NOT EXISTS vector',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('filename', models.CharField(max_length=500)),
                ('original_filename', models.CharField(max_length=500)),
                (
                    'doc_type',
                    models.CharField(
                        choices=[
                            ('policy', 'Policy'),
                            ('contract', 'Contract'),
                            ('procedure', 'Procedure'),
                            ('specification', 'Specification'),
                        ],
                        max_length=20,
                    ),
                ),
                ('file_size', models.BigIntegerField()),
                ('total_chunks', models.IntegerField(default=0)),
                ('cloudinary_url', models.URLField(max_length=1000)),
                ('ingested_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'uploaded_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='uploaded_documents',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('chunk_text', models.TextField()),
                (
                    'embedding',
                    pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
                ),
                (
                    'tsvector',
                    django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
                ),
                ('source_document', models.CharField(max_length=500)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                (
                    'document',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='chunks',
                        to='ingestion.document',
                    ),
                ),
            ],
            options={
                'verbose_name': 'document chunk',
                'verbose_name_plural': 'document chunks',
                'ordering': ['document', 'id'],
                'indexes': [
                    models.Index(fields=['source_document'], name='ingestion_d_source__e0c16e_idx'),
                    models.Index(fields=['document'], name='ingestion_d_documen_7c5c8a_idx'),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=['tsvector'], name='document_chunk_gin_idx'
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name='InvoiceScan',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('original_filename', models.CharField(max_length=500)),
                ('content_type', models.CharField(max_length=100)),
                ('file_size', models.BigIntegerField()),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('extracted', 'Extracted'),
                            ('partial', 'Partial'),
                            ('failed', 'Failed'),
                            ('confirmed', 'Confirmed'),
                            ('rejected', 'Rejected'),
                        ],
                        default='pending',
                        max_length=20,
                    ),
                ),
                ('extracted_data', models.JSONField(default=dict)),
                ('confidence', models.JSONField(default=dict)),
                ('missing_fields', models.JSONField(default=list)),
                ('failure_reason', models.TextField(blank=True)),
                ('confirmed_data', models.JSONField(default=dict)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'uploaded_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='invoice_scans',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'invoice scan',
                'verbose_name_plural': 'invoice scans',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(
                        fields=['uploaded_by', 'status'], name='ingestion_i_uploade_300c12_idx'
                    ),
                    models.Index(fields=['created_at'], name='ingestion_i_created_027a4f_idx'),
                ],
            },
        ),
    ]
