# Generated by Django 5.0.14 on 2026-06-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
