# Generated by Django 5.0.14 on 2026-06-11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ingestion', '0003_pgvector_extension'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceScan',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('original_filename', models.CharField(max_length=500)),
                ('content_type', models.CharField(max_length=100)),
                ('file_size', models.BigIntegerField()),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('extracted', 'Extracted'),
                            ('partial', 'Partial'),
                            ('failed', 'Failed'),
                            ('confirmed', 'Confirmed'),
                            ('rejected', 'Rejected'),
                        ],
                        default='pending',
                        max_length=20,
                    ),
                ),
                ('extracted_data', models.JSONField(default=dict)),
                ('confidence', models.JSONField(default=dict)),
                ('missing_fields', models.JSONField(default=list)),
                ('failure_reason', models.TextField(blank=True)),
                ('confirmed_data', models.JSONField(default=dict)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'uploaded_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='invoice_scans',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(
                        fields=['uploaded_by', 'status'], name='ingestion_i_uploade_bda6d0_idx'
                    ),
                    models.Index(fields=['created_at'], name='ingestion_i_created_f37035_idx'),
                ],
            },
        ),
    ]
