# Generated by Django 5.0.14 on 2026-06-13 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0004_invoicescan'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='invoicescan',
            new_name='ingestion_i_uploade_300c12_idx',
            old_name='ingestion_i_uploade_bda6d0_idx',
        ),
        migrations.RenameIndex(
            model_name='invoicescan',
            new_name='ingestion_i_created_027a4f_idx',
            old_name='ingestion_i_created_f37035_idx',
        ),
    ]
