# Generated by Django 5.0.14 on 2026-06-17 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0006_documentchunk_embedding_hnsw'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at'], 'verbose_name': 'document', 'verbose_name_plural': 'documents'},
        ),
        migrations.AlterModelOptions(
            name='documentchunk',
            options={'ordering': ['document', 'id'], 'verbose_name': 'document chunk', 'verbose_name_plural': 'document chunks'},
        ),
        migrations.AlterModelOptions(
            name='invoicescan',
            options={'ordering': ['-created_at'], 'verbose_name': 'invoice scan', 'verbose_name_plural': 'invoice scans'},
        ),
    ]
