[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.prod"

[deploy]
startCommand = "celery -A config worker --loglevel=info --pool=solo --concurrency=1 --without-mingle --without-gossip"
restartPolicyType = "ON_FAILURE"
