[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.prod"

[deploy]
startCommand = "celery -A config worker --loglevel=info --pool=threads --concurrency=4 --without-mingle --without-gossip"
restartPolicyType = "ON_FAILURE"
