# Generated by Django 5.0.14 on 2026-06-17 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('predicted_quantity', models.FloatField()),
                ('lower_bound', models.FloatField(blank=True, null=True)),
                ('upper_bound', models.FloatField(blank=True, null=True)),
                ('mae', models.FloatField(blank=True, null=True)),
                ('mape', models.FloatField(blank=True, null=True)),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='inventory.sku')),
            ],
            options={
                'verbose_name': 'forecast result',
                'verbose_name_plural': 'forecast results',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['sku', 'forecast_date'], name='forecasting_sku_id_7efcbd_idx')],
                'unique_together': {('sku', 'forecast_date')},
            },
        ),
        migrations.CreateModel(
            name='ReorderFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_available', models.IntegerField()),
                ('total_predicted_demand', models.FloatField()),
                ('safety_stock', models.IntegerField(default=0)),
                ('lead_time_days', models.IntegerField(default=7)),
                ('forecast_days', models.IntegerField(default=7)),
                ('reorder_required', models.BooleanField(default=True)),
                ('has_open_po', models.BooleanField(default=False)),
                ('open_po_id', models.IntegerField(blank=True, null=True)),
                ('reasoning', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('consumed', 'Consumed'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_flags', to='inventory.sku')),
            ],
            options={
                'verbose_name': 'reorder flag',
                'verbose_name_plural': 'reorder flags',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['sku', 'status'], name='forecasting_sku_id_603fff_idx'), models.Index(fields=['created_at'], name='forecasting_created_522cf9_idx')],
            },
        ),
    ]
