# Generated by Django 5.0.14 on 2026-06-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
