# Generated by Django 5.0.14 on 2026-06-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('forecasting', '0001_initial'),
        ('inventory', '0002_remove_salesrecord_inventory_s_sku_id_92dcd2_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='forecastresult',
            name='forecasting_sku_id_7efcbd_idx',
        ),
        migrations.AddIndex(
            model_name='forecastresult',
            index=models.Index(fields=['forecast_date'], name='forecasting_forecas_6afc55_idx'),
        ),
    ]
