# Generated by Django 5.0.14 on 2026-06-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0001_initial'),
        ('inventory', '0002_supplier_salesrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastresult',
            name='mae',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forecastresult',
            name='mape',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='forecastresult',
            unique_together={('sku', 'forecast_date')},
        ),
    ]
