# Generated by Django 5.0.14 on 2026-06-11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0002_forecastresult_updated_at'),
        ('inventory', '0003_alter_salesrecord_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReorderFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_available', models.IntegerField()),
                ('total_predicted_demand', models.FloatField()),
                ('safety_stock', models.IntegerField(default=0)),
                ('lead_time_days', models.IntegerField(default=7)),
                ('forecast_days', models.IntegerField(default=7)),
                ('reorder_required', models.BooleanField(default=True)),
                ('has_open_po', models.BooleanField(default=False)),
                ('open_po_id', models.IntegerField(blank=True, null=True)),
                ('reasoning', models.TextField()),
                (
                    'status',
                    models.CharField(
                        choices=[('open', 'Open'), ('consumed', 'Consumed'), ('dismissed', 'Dismissed')],
                        default='open',
                        max_length=20,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'sku',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='reorder_flags',
                        to='inventory.sku',
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['sku', 'status'], name='forecasting_sku_id_a18a43_idx'),
                    models.Index(fields=['created_at'], name='forecasting_created_18d832_idx'),
                ],
            },
        ),
    ]
