# Generated by Django 5.0.14 on 2026-06-12 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forecasting", "0003_reorderflag"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="forecastresult",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameIndex(
            model_name="reorderflag",
            new_name="forecasting_sku_id_603fff_idx",
            old_name="forecasting_sku_id_a18a43_idx",
        ),
        migrations.RenameIndex(
            model_name="reorderflag",
            new_name="forecasting_created_522cf9_idx",
            old_name="forecasting_created_18d832_idx",
        ),
    ]
