# Generated by Django 5.0.14 on 2026-06-13 18:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('forecasting', '0004_alter_forecastresult_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecastresult',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
