# Generated by Django 5.0.14 on 2026-06-17 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0005_alter_forecastresult_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecastresult',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'forecast result', 'verbose_name_plural': 'forecast results'},
        ),
        migrations.AlterModelOptions(
            name='reorderflag',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'reorder flag', 'verbose_name_plural': 'reorder flags'},
        ),
    ]
