# Generated by Django 5.0.14 on 2026-06-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='salesrecord',
            name='inventory_s_sku_id_92dcd2_idx',
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['name'], name='inventory_s_name_d435cf_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['is_active'], name='inventory_s_is_acti_3743da_idx'),
        ),
    ]
