# Generated by Django 5.0.14 on 2026-06-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_warehouse_capacity',
            field=models.IntegerField(default=1000),
        ),
    ]
