# Generated by Django 5.0.14 on 2026-06-08 11:40

import django.db.models.deletion
from django.db import migrations, models


def migrate_category_data(apps, schema_editor):
    Product = apps.get_model('inventory', 'Product')
    Category = apps.get_model('inventory', 'Category')
    db_alias = schema_editor.connection.alias
    cat_map = {}
    for p in Product.objects.using(db_alias).values('category').distinct():
        name = p['category']
        if name and name not in cat_map:
            cat, _ = Category.objects.using(db_alias).get_or_create(name=name)
            cat_map[name] = cat.id
    for name, cat_id in cat_map.items():
        Product.objects.using(db_alias).filter(category=name).update(category=cat_id)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_supplier_salesrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.RemoveField(
            model_name='stocklevel',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_point',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='product',
            name='safety_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.supplier'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_of_measure',
            field=models.CharField(blank=True, default='units', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stocklevel',
            name='quantity_on_hand',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(
            migrate_category_data, reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.category'),
        ),
    ]
