# Generated by Django 5.0.14 on 2026-06-11 09:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0002_product_max_warehouse_capacity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesrecord',
            options={'ordering': ['-date', 'sku']},
        ),
    ]
