# Generated by Django 5.0.14 on 2026-06-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0003_alter_salesrecord_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(
                fields=['is_active', '-created_at'], name='idx_product_active_created'
            ),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='idx_product_name'),
        ),
        migrations.AddIndex(
            model_name='stocklevel',
            index=models.Index(fields=['quantity_on_hand'], name='idx_stocklevel_qty'),
        ),
        migrations.AddIndex(
            model_name='stocklevel',
            index=models.Index(
                fields=['quantity_on_hand', 'reorder_point'], name='idx_stocklevel_low'
            ),
        ),
    ]
