# Generated by Django 5.0.14 on 2026-06-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_idx_product_active_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_at'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='salesrecord',
            options={'ordering': ['-date', 'sku'], 'verbose_name': 'sales record', 'verbose_name_plural': 'sales records'},
        ),
        migrations.AlterModelOptions(
            name='sku',
            options={'ordering': ['-created_at'], 'verbose_name': 'SKU', 'verbose_name_plural': 'SKUs'},
        ),
        migrations.AlterModelOptions(
            name='stocklevel',
            options={'ordering': ['-updated_at'], 'verbose_name': 'stock level', 'verbose_name_plural': 'stock levels'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['-created_at'], 'verbose_name': 'supplier', 'verbose_name_plural': 'suppliers'},
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
