# Generated by Django 5.0.14 on 2026-06-17 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escalationnotification',
            options={'ordering': ['-created_at'], 'verbose_name': 'escalation notification', 'verbose_name_plural': 'escalation notifications'},
        ),
    ]
