# Generated by Django 5.0.14 on 2026-06-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dashboardbanner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
