# Generated by Django 5.0.14 on 2026-06-14 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agentrunlog',
            new_name='monitoring__agent_n_d59d21_idx',
            old_name='monitoring__agent_idx',
        ),
        migrations.RenameIndex(
            model_name='agentrunlog',
            new_name='monitoring__created_cc0697_idx',
            old_name='monitoring__arun_c_idx',
        ),
        migrations.RenameIndex(
            model_name='alertevent',
            new_name='monitoring__rule_id_aaeb3e_idx',
            old_name='monitoring__rule_st_idx',
        ),
        migrations.RenameIndex(
            model_name='alertevent',
            new_name='monitoring__created_c5d441_idx',
            old_name='monitoring__created_idx',
        ),
        migrations.RenameIndex(
            model_name='dashboardbanner',
            new_name='monitoring__dismiss_c2e824_idx',
            old_name='monitoring__dismiss_idx',
        ),
        migrations.RenameIndex(
            model_name='tokenusagelog',
            new_name='monitoring__logged__724f87_idx',
            old_name='monitoring__logged_idx',
        ),
    ]
