# Generated by Django 5.0.14 on 2026-06-17 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_rename_monitoring__agent_idx_monitoring__agent_n_d59d21_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentrunlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'agent run log', 'verbose_name_plural': 'agent run logs'},
        ),
        migrations.AlterModelOptions(
            name='alertevent',
            options={'ordering': ['-created_at'], 'verbose_name': 'alert event', 'verbose_name_plural': 'alert events'},
        ),
        migrations.AlterModelOptions(
            name='alertrule',
            options={'ordering': ['name'], 'verbose_name': 'alert rule', 'verbose_name_plural': 'alert rules'},
        ),
        migrations.AlterModelOptions(
            name='dashboardbanner',
            options={'ordering': ['-created_at'], 'verbose_name': 'dashboard banner', 'verbose_name_plural': 'dashboard banners'},
        ),
        migrations.AlterModelOptions(
            name='tokenusagelog',
            options={'ordering': ['-created_at'], 'verbose_name': 'token usage log', 'verbose_name_plural': 'token usage logs'},
        ),
    ]
